# Generated by Django 4.0.4 on 2022-05-14 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='title',
            field=models.CharField(default=1212, max_length=120),
            preserve_default=False,
        ),
    ]
